import { PrismaClient } from '../generated/prisma';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding dummy data...');

  // 1. Seed some dummy knowledge base documents
  console.log('Creating Documents...');
  
  // Create an Employee Handbook document
  const handbookDoc = await prisma.document.create({
    data: {
      title: 'Employee Handbook 2026',
      content: 'Welcome to Nexus Enterprise! Our core working hours are 10 AM to 4 PM. We offer 4 weeks of paid time off per year. Health insurance benefits begin on day one of employment. For any IT issues, please submit a ticket through the internal portal.',
    },
  });

  // Create a Project Architecture document
  const architectureDoc = await prisma.document.create({
    data: {
      title: 'Nexus Architecture Overview',
      content: 'Nexus is built on a modern stack using Next.js 15 for the frontend, Prisma ORM for database interactions, and a PostgreSQL database with the pgvector extension for AI similarity search. The application uses LangGraph to orchestrate multi-step AI workflows.',
    },
  });

  // 2. Seed document chunks (normally these would be generated by splitting the document and using an AI to create embeddings)
  // For dummy data, we will just create some chunks without actual embeddings (since pgvector allows nulls if configured or we can skip it if it's optional).
  // Note: The embedding field in schema.prisma is optional: `embedding  Unsupported("vector(1536)")?`
  console.log('Creating Document Chunks...');

  await prisma.documentChunk.create({
    data: {
      documentId: handbookDoc.id,
      content: 'Welcome to Nexus Enterprise! Our core working hours are 10 AM to 4 PM.',
    },
  });

  await prisma.documentChunk.create({
    data: {
      documentId: handbookDoc.id,
      content: 'We offer 4 weeks of paid time off per year. Health insurance benefits begin on day one of employment.',
    },
  });

  await prisma.documentChunk.create({
    data: {
      documentId: architectureDoc.id,
      content: 'Nexus is built on a modern stack using Next.js 15 for the frontend, Prisma ORM for database interactions, and a PostgreSQL database with the pgvector extension.',
    },
  });

  // 3. Seed some dummy chat sessions to demonstrate conversation history
  console.log('Creating Chat Sessions...');

  const chat1 = await prisma.chatSession.create({
    data: {
      title: 'Questions about PTO',
      messages: {
        create: [
          { role: 'user', content: 'How much paid time off do I get?' },
          { role: 'assistant', content: 'You receive 4 weeks of paid time off per year.' },
        ],
      },
    },
  });

  const chat2 = await prisma.chatSession.create({
    data: {
      title: 'Tech Stack Inquiry',
      messages: {
        create: [
          { role: 'user', content: 'What database are we using?' },
          { role: 'assistant', content: 'We are using a PostgreSQL database with the pgvector extension.' },
        ],
      },
    },
  });

  console.log('Seeding complete! Dummy data added successfully.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
